In [427]:
import torch

device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps" if torch.backends.mps.is_available() else "cpu"
)
device

'mps'

# Tensor

## Creating tensors


In [372]:
# scalar
scalar = torch.tensor(3.14159)
scalar

tensor(3.1416)

In [373]:
scalar.ndim

0

In [374]:
# Get tensor back as integer
scalar.item()

3.141590118408203

In [375]:
# vector
vector = torch.tensor([4, 4])
vector.ndim

1

In [376]:
vector.shape

torch.Size([2])

In [377]:
# Matrix
MATRIX = torch.tensor([[1, 2], [3, 4]])
MATRIX.ndim

2

In [378]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
TENSOR.ndim

3

In [379]:
TENSOR.shape

torch.Size([2, 2, 3])

## Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent tha data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


In [380]:
# Create a random tensors of shape (3, 4)
rand_tensor = torch.rand(3, 4)
rand_tensor

tensor([[0.3715, 0.5909, 0.2039, 0.6770],
        [0.5014, 0.4132, 0.3412, 0.0075],
        [0.7051, 0.5503, 0.2005, 0.3368]])

In [381]:
# Create a random tensor with similar shape to an image tensor
rand_img_size_tensor = torch.rand(
    size=(224, 224, 3)
)  # height, width, channels (R, G, B)
rand_img_size_tensor.shape, rand_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zero and Ones tensors


In [382]:
zero = torch.zeros(3, 4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [383]:
zero * rand_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [384]:
ones = torch.ones(3, 4)
ones * rand_tensor

tensor([[0.3715, 0.5909, 0.2039, 0.6770],
        [0.5014, 0.4132, 0.3412, 0.0075],
        [0.7051, 0.5503, 0.2005, 0.3368]])

## Creating a range of tensors and tensors-like objects


In [385]:
one_to_ten = torch.arange(start=0, end=10, step=1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [386]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor data types

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep Learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device


In [387]:
float_32_tensor = torch.tensor(
    [1, 2, 3], dtype=torch.float32, device=device, requires_grad=False
)
float_32_tensor

tensor([1., 2., 3.], device='mps:0')

In [388]:
float_16_tensor = float_32_tensor.to(torch.float16)
float_16_tensor

tensor([1., 2., 3.], device='mps:0', dtype=torch.float16)

In [389]:
float_32_tensor * float_16_tensor

tensor([1., 4., 9.], device='mps:0')

## Getting information from tensors

When dealing with tensors you'll want to be able to quickly identify the following attributes:

1. Datatype of the tensor: `tensor.dtype`
2. Shape of the tensor: `tensor.shape`
3. Device of the tensor: `tensor.device`


In [390]:
some_tensor = torch.rand(size=(3, 4), device=device)
some_tensor.dtype, some_tensor.device, some_tensor.shape

(torch.float32, device(type='mps', index=0), torch.Size([3, 4]))

## Manipulating tensors (tensor operations)


In [391]:
some_tensor + 100

tensor([[100.7508, 100.0519, 100.7472, 100.9533],
        [100.0367, 100.1026, 100.8028, 100.7164],
        [100.2109, 100.9684, 100.6037, 100.7722]], device='mps:0')

In [392]:
torch.mul(some_tensor, 10)

tensor([[7.5081, 0.5190, 7.4724, 9.5326],
        [0.3672, 1.0257, 8.0282, 7.1644],
        [2.1091, 9.6842, 6.0369, 7.7221]], device='mps:0')

In [393]:
torch.matmul(some_tensor.T, some_tensor)

tensor([[0.6096, 0.2470, 0.7178, 0.9049],
        [0.2470, 0.9510, 0.7058, 0.8708],
        [0.7178, 0.7058, 1.5673, 1.7537],
        [0.9049, 0.8708, 1.7537, 2.0183]], device='mps:0')

In [394]:
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_B = torch.tensor([[7, 8], [9, 10], [11, 12]])
torch.mm(tensor_A, tensor_B.T)  # Transpose tensor_B to match inner dimensions

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

## Finding the min, max, mean, sum, etc (tensor aggregation)


In [395]:
x = torch.arange(0, 100, 10)
torch.min(x), x.min()

(tensor(0), tensor(0))

In [396]:
# Find the mean - the torch.mean() func requires a tensor of float dtype
torch.mean(x.float()), x.float().mean()

(tensor(45.), tensor(45.))

In [397]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [398]:
x.argmax(), x.argmin()  # Returns the index of the maximum and minimum value in the tensor_A

(tensor(9), tensor(0))

## Reshaping, stacking, squeezing, and unsqueezing tensors

-   Reshaping: reshapes an input tensor to a defined shape
-   View: returns a view of an input tensor of certain shape but keep the same memory as the original tensor
-   Stacking: combines multiple tensors on top of each other (vstack) or side by side (hstack)
-   Squeeze: removes all `1` dimensions from a tensor
-   Unsqueeze: adds a dimension with a size of `1` to a tensor
-   Permute: returns a view of the input with dimensions permuted (swapped) as per the desired ordering


In [399]:
import torch

x = torch.arange(1.0, 10.0)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [400]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [401]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [402]:
# Stack tensors on top of each other at a specific dimension
stacked = torch.stack([x, x, x], dim=1)
stacked, stacked.shape

(tensor([[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.],
         [5., 5., 5.],
         [6., 6., 6.],
         [7., 7., 7.],
         [8., 8., 8.],
         [9., 9., 9.]]),
 torch.Size([9, 3]))

In [403]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [404]:
x_squeezed = x_reshaped.squeeze()
x_squeezed.unsqueeze(dim=0), x_squeezed.unsqueeze(dim=0).shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [405]:
x_original = torch.rand(size=(224, 224, 3))  # height, width, channels (R, G, B)
x_permuted = x_original.permute(
    2, 0, 1
)  # Shifts axis 0 -> 1, 1 -> 2, 2 -> 0: channels, height, width
x_permuted.shape  # Shares the same memory as x_original

torch.Size([3, 224, 224])

## Indexing (Selecting data from tensors)


In [406]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [407]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [408]:
x[0][0]

tensor([1, 2, 3])

In [409]:
x[0][0][0]

tensor(1)

In [410]:
# Use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [411]:
# Get all values of 0th and 1st dimensions but only index 1 of the 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [412]:
# Get all values of the 0 dimension but only 1 index value of 1st and 2nd dimensions
x[:, 1, 1]

tensor([5])

In [413]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch tensors & NumPy

-   Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
-   PyTorch tensor -> NumPy -> `torch_tensor.numpy()`


In [414]:
# NumPy array to PyTorch tensor
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).float()
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [415]:
# Change the value of array, what will happen to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [416]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (Trying to take random out of random)

IN short how a neuron network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "Flavour the randomness.


In [419]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
rand_tensor_A = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
rand_tensor_B = torch.rand(3, 4)

rand_tensor_A, rand_tensor_B, rand_tensor_A == rand_tensor_B

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

tensor([ 1,  0,  0,  0,  1,  0,  0,  0,  1,  0,  0,  0,  1,  0,  0,  0,  1,  0,
         0,  0, 42,  0,  0,  0,  0,  0,  0,  0, 42,  0,  0,  0,  0,  0,  0,  0],
       dtype=torch.uint8)